"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.chrome = exports.safari = exports.firefox = void 0;
exports.firefox = {
    codecs: [
        {
            mimeType: "audio/opus",
            kind: "audio",
            preferredPayloadType: 111,
            clockRate: 48000,
            channels: 2,
            parameters: { maxplaybackrate: 48000, stereo: 1, useinbandfec: 1 },
            rtcpFeedback: [],
        },
        {
            mimeType: "video/VP8",
            kind: "video",
            preferredPayloadType: 96,
            clockRate: 90000,
            channels: undefined,
            parameters: { "max-fs": 12288, "max-fr": 60 },
            rtcpFeedback: [
                { type: "nack", parameter: "" },
                { type: "nack", parameter: "pli" },
                { type: "ccm", parameter: "fir" },
            ],
        },
        {
            mimeType: "video/H264",
            kind: "video",
            preferredPayloadType: 125,
            clockRate: 90000,
            channels: undefined,
            parameters: {
                "profile-level-id": "42e01f",
                "level-asymmetry-allowed": 1,
                "packetization-mode": 1,
            },
            rtcpFeedback: [
                { type: "nack", parameter: "" },
                { type: "nack", parameter: "pli" },
                { type: "ccm", parameter: "fir" },
            ],
        },
    ],
    headerExtensions: [
        {
            kind: "audio",
            uri: "urn:ietf:params:rtp-hdrext:sdes:mid",
            preferredId: 1,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
        {
            kind: "video",
            uri: "urn:ietf:params:rtp-hdrext:sdes:mid",
            preferredId: 1,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
        {
            kind: "video",
            uri: "http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time",
            preferredId: 4,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
        {
            kind: "audio",
            uri: "urn:ietf:params:rtp-hdrext:ssrc-audio-level",
            preferredId: 10,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
        {
            kind: "video",
            uri: "urn:ietf:params:rtp-hdrext:toffset",
            preferredId: 12,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
    ],
};
exports.safari = {
    codecs: [
        {
            mimeType: "audio/opus",
            kind: "audio",
            preferredPayloadType: 111,
            clockRate: 48000,
            channels: 2,
            parameters: { minptime: 10, useinbandfec: 1 },
            rtcpFeedback: [{ type: "transport-cc", parameter: "" }],
        },
        {
            mimeType: "video/VP8",
            kind: "video",
            preferredPayloadType: 96,
            clockRate: 90000,
            channels: undefined,
            parameters: {},
            rtcpFeedback: [
                { type: "transport-cc", parameter: "" },
                { type: "ccm", parameter: "fir" },
                { type: "nack", parameter: "" },
                { type: "nack", parameter: "pli" },
            ],
        },
        {
            mimeType: "video/rtx",
            kind: "video",
            preferredPayloadType: 100,
            clockRate: 90000,
            parameters: { apt: 96 },
            rtcpFeedback: [],
        },
        {
            mimeType: "video/H264",
            kind: "video",
            preferredPayloadType: 125,
            clockRate: 90000,
            channels: undefined,
            parameters: {
                "level-asymmetry-allowed": 1,
                "packetization-mode": 1,
                "profile-level-id": "42e01f",
            },
            rtcpFeedback: [
                { type: "transport-cc", parameter: "" },
                { type: "ccm", parameter: "fir" },
                { type: "nack", parameter: "" },
                { type: "nack", parameter: "pli" },
            ],
        },
        {
            mimeType: "video/rtx",
            kind: "video",
            preferredPayloadType: 101,
            clockRate: 90000,
            parameters: { apt: 125 },
            rtcpFeedback: [],
        },
    ],
    headerExtensions: [
        {
            kind: "audio",
            uri: "urn:ietf:params:rtp-hdrext:sdes:mid",
            preferredId: 1,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
        {
            kind: "video",
            uri: "urn:ietf:params:rtp-hdrext:sdes:mid",
            preferredId: 1,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
        {
            kind: "audio",
            uri: "http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time",
            preferredId: 4,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
        {
            kind: "video",
            uri: "http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time",
            preferredId: 4,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
        {
            kind: "video",
            uri: "http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01",
            preferredId: 5,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
        {
            kind: "video",
            uri: "http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07",
            preferredId: 6,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
        {
            kind: "audio",
            uri: "urn:ietf:params:rtp-hdrext:ssrc-audio-level",
            preferredId: 10,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
        {
            kind: "video",
            uri: "urn:3gpp:video-orientation",
            preferredId: 11,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
        {
            kind: "video",
            uri: "urn:ietf:params:rtp-hdrext:toffset",
            preferredId: 12,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
    ],
};
exports.chrome = {
    codecs: [
        {
            mimeType: "audio/opus",
            kind: "audio",
            preferredPayloadType: 111,
            clockRate: 48000,
            channels: 2,
            parameters: { minptime: 10, useinbandfec: 1 },
            rtcpFeedback: [{ type: "transport-cc", parameter: "" }],
        },
        {
            mimeType: "video/VP8",
            kind: "video",
            preferredPayloadType: 96,
            clockRate: 90000,
            channels: undefined,
            parameters: {},
            rtcpFeedback: [
                { type: "transport-cc", parameter: "" },
                { type: "ccm", parameter: "fir" },
                { type: "nack", parameter: "" },
                { type: "nack", parameter: "pli" },
            ],
        },
        {
            mimeType: "video/rtx",
            kind: "video",
            preferredPayloadType: 100,
            clockRate: 90000,
            parameters: { apt: 96 },
            rtcpFeedback: [],
        },
        {
            mimeType: "video/H264",
            kind: "video",
            preferredPayloadType: 125,
            clockRate: 90000,
            channels: undefined,
            parameters: {
                "level-asymmetry-allowed": 1,
                "packetization-mode": 1,
                "profile-level-id": "42e01f",
            },
            rtcpFeedback: [
                { type: "transport-cc", parameter: "" },
                { type: "ccm", parameter: "fir" },
                { type: "nack", parameter: "" },
                { type: "nack", parameter: "pli" },
            ],
        },
        {
            mimeType: "video/rtx",
            kind: "video",
            preferredPayloadType: 101,
            clockRate: 90000,
            parameters: { apt: 125 },
            rtcpFeedback: [],
        },
    ],
    headerExtensions: [
        {
            kind: "audio",
            uri: "urn:ietf:params:rtp-hdrext:sdes:mid",
            preferredId: 1,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
        {
            kind: "video",
            uri: "urn:ietf:params:rtp-hdrext:sdes:mid",
            preferredId: 1,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
        {
            kind: "audio",
            uri: "http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time",
            preferredId: 4,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
        {
            kind: "video",
            uri: "http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time",
            preferredId: 4,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
        {
            kind: "video",
            uri: "http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01",
            preferredId: 5,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
        {
            kind: "video",
            uri: "http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07",
            preferredId: 6,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
        {
            kind: "audio",
            uri: "urn:ietf:params:rtp-hdrext:ssrc-audio-level",
            preferredId: 10,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
        {
            kind: "video",
            uri: "urn:3gpp:video-orientation",
            preferredId: 11,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
        {
            kind: "video",
            uri: "urn:ietf:params:rtp-hdrext:toffset",
            preferredId: 12,
            preferredEncrypt: false,
            direction: "sendrecv",
        },
    ],
};
//# sourceMappingURL=BrowserRtpCapabilities.js.map