branches:
  only:
  - v3

language: node_js

node_js:
- 10
- 12
- 14

install:
- npm install

script:
- npm run lint
- npm run typescript:build
- npm test

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - secure: nZrn+wwkyo7sLlB9/Gsk4CyzyG3UccqOimQRz5VwTwyafYqpwin5T6eWBoDq6nphfLPt4D9keC4NawRlv2bX9AWRuKlrU7Z8/1rkObIwSm1ZNk/Yn718Q/IwEDSabS00pNXV3X9dV1QfxelrHiH1PgNdjU1aOyMqWWD445aXq/RM8L6ushksMbMkoW6DWaM83DGFB2FWumkFqI84uRpWqdESp9mVVErxBeWrTAOQqRsLDHGFwcDq07xBJDNw7vrPN2Furnf3xE6hGDWiBpstjwGpY0vql+5UzjOnC6oqdLP9H3i5znR2lzPw5x/4S0cW6fKzF/G02aPPk2Oty9CRXdLJKuJ9Xrwo7BVAEfnQFpc6q1kvONx/j0bY2UdLO2zgUGM1IWO2Pvmm7//FWiv9WgCF3kfOIp5qh5SN1o/W+SErmvKaYyOPMe3OUOemDjOnVIQcMDTISue2aYUS7GuoTx/+jp+F8Y99/3shyBWEaAbg1LVptRgMUvSzrBG/3Y2b6Gx2qSojMisyqfv3USx8h91sxZ96qyHkbHm4LCzB6PeRgNf+ebUnm/+fTrTtkdeo3byD5ZsKI1dzJ+/ZqDaAEEZRKwLxBdJLlLsWAoM+iQ4L6rPgFP5xZ2E4eVQY/MPJt3bjCxEhNSc/8y1vTIozx33PoiemILODj+I/ARxYxB8=
    - secure: dSfH0lbTzxCBjMnZdg1nBy3i7BVtLpiM+1PkWcj3FrLwNVDc6yjNmsqxF+AwDJRYlsq/KtaZIKx8GeTIz59LpOnXunFugnpl2XnJAw+QdNYsTRnfj99PlbGaZFoqL5p1l/8zJxRcuIiaIlpE3yV5iD7pT35DoTY/WWew/6Wcu1aawWUwJ6oR4y/K8hyN0J8GaWb62HTmdwPWY0mc1qtCHVGDWGAQXi828U7QhQpXmk9e8G8j3a9yiVAHI3hFzgUkQv2qBil/1NHr9RY4J/bOuiWymBfDTzyfOdJgn2nZUD+ky+UucEqVnzUE9kvNYkOHUTzq3+H5LLgUy8n4uSIwhvYsGNVgpJCQufc4F+GM70bEA+jCB+pihiBDLN2o2vpbNH45vi8zZtW1bUIdJC88MMjiKC4Yvu33n0ii0/1arqUK9Na96phYJUpgbz6nCKBRO0N/VlXwZTvwJ5hmIhoYzZ9vrvXD66RMGB+Bbm318TvOJqCUEoNRyTaXcBFBr0vEgq3+vTlnOGcxv83efHP8+GUM7Q3f22N4GHXBtIlRIYVtcEm5PjYtdtvzAup2Upr3Y8UnaYhq8SJREZIBEFfNRPB3g0/knizmls0zIzoXvakOtsUq+sUt5xapayD8RYiN4W/Kj8fhWKFUL+zby6OJx+bC9MTA+LVRhROKdLhvga8=
