export const DataProtocol = {
    ToStreamer: {
        IFrameRequest: { id: 0, structure: [] },
        RequestQualityControl: { id: 1, structure: [] },
        FpsRequest: { id: 2, structure: [] },
        AverageBitrateRequest: { id: 3, structure: [] },
        StartStreaming: { id: 4, structure: [] },
        StopStreaming: { id: 5, structure: [] },
        LatencyTest: { id: 6, structure: [ "string" ] },
        RequestInitialSettings: { id: 7, structure: [] },
        TestEcho: { id: 8, structure: [ "string" ] },
        UIInteraction: { id: 50, structure: [] },
        Command: { id: 51, structure: [ "string" ] },
        TextboxEntry: { id: 52, structure: [ "string" ] },
        KeyDown: { id: 60, structure: [ "uint8", "uint8" ] },
        KeyUp: { id: 61, structure: [ "uint8" ] },
        KeyPress: { id: 62, structure: [ "uint16" ] },
        MouseEnter: { id: 70, structure: [] },
        MouseLeave: { id: 71, structure: [] },
        MouseDown: { id: 72, structure: [ "uint8", "uint16", "uint16" ] },
        MouseUp: { id: 73, structure: [ "uint8", "uint16", "uint16" ] },
        MouseMove: { id: 74, structure: [ "uint16", "uint16", "uint16", "uint16" ] },
        MouseWheel: { id: 75, structure: [ "int16", "uint16", "uint16" ] },
        MouseDouble: { id: 76, structure: [ "uint8", "uint16", "uint16" ] },
        TouchStart: { id: 80, structure: [ "uint8", "uint16", "uint16", "uint8", "uint8", "uint8" ] },
        TouchEnd: { id: 81, structure: [ "uint8", "uint16", "uint16", "uint8", "uint8", "uint8" ] },
        TouchMove: { id: 82, structure: [ "uint8", "uint16", "uint16", "uint8", "uint8", "uint8" ] },
        GamepadButtonPressed: { id: 90, structure: [ "uint8", "uint8", "uint8" ] },
        GamepadButtonReleased: { id: 91, structure: [ "uint8", "uint8", "uint8" ] },
        GamepadAnalog: { id: 92, structure: [ "uint8", "uint8", "double" ] },
        GamepadConnected: { id: 93, structure: [] },
        GamepadDisconnected: { id: 94, structure: [ "uint8" ] },
    },
    FromStreamer: {
        QualityControlOwnership: { id: 0, structure: [] },
        Response: { id: 1, structure: [] },
        Command: { id: 2, structure: [] },
        FreezeFrame: { id: 3, structure: [] },
        UnfreezeFrame: { id: 4, structure: [] },
        VideoEncoderAvgQP: { id: 5, structure: [] },
        LatencyTest: { id: 6, structure: [] },
        InitialSettings: { id: 7, structure: [ "only_string" ] },
        FileExtension: { id: 8, structure: [] },
        FileMimeType: { id: 9, structure: [] },
        FileContents: { id: 10, structure: [] },
        TestEcho: { id: 11, structure: [] },
        InputControlOwnership: { id: 12, structure: [] },
        GamepadResponse: { id: 13, structure: [] },
        Protocol: { id: 255, structure: [ "only_string" ] },
    }
};
