name: Check health of document links

on: 
  workflow_dispatch:
  pull_request:
    paths:
      - "**.md" # Trigger only when md files are in a PR
  push:
    paths:
      - '**.md'  # Trigger only when md files are pushed

permissions:
  contents: read
  issues: write

jobs:
  linkChecker:
    if: github.repository == 'EpicGamesExt/PixelStreamingInfrastructure'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          args: --user-agent 'GHA/PixelStreamingInfrastructure' --accept '100..=103,200..=299,403,429' --github-token ${{ secrets.WORKFLOW_TOKEN }} --exclude 'localhost' --exclude 'github.com/EpicGames/UnrealEngine' --exclude '.png' --exclude '.jpg' --exclude-path 'SFU/mediasoup-sdp-bridge/README.md' './**/*.md'

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
